# Forward Propagation

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
# define activation functions
def sigmoid(z):
    return 1.0/(1.0 + np.exp(-z)) 
def relu(z):
    return np.maximum(z, 0)

In [15]:
# define Layer Class
class Layer:
    
    def __init__(self,n_inputs,n_neurons):
        np.random.seed(21)
        self.weights = np.random.randn(n_neurons,n_inputs)
        self.biases = np.zeros((n_neurons,1))
        
    def update_params(self,new_weights,new_biases):
        self.weights = new_weights
        self.biases = new_biases
        
    def forward(self,inputs,phi):
        self.outputs = phi(np.dot(self.weights,inputs)+self.biases)
        return self.outputs

In [4]:
x1 = np.array([[2.3,4.5,1.3]])
x1 = x1.T

W1 = np.array([[3.2,-1.9,2.5],[.2,-.3,.2]])
b1 = np.array([[-1],[1]])

In [5]:
L1 = Layer(3,2)
L2 = Layer(2,1)

In [9]:
L1.update_params(W1,b1)

In [10]:
L1.weights

array([[ 3.2, -1.9,  2.5],
       [ 0.2, -0.3,  0.2]])

In [11]:
L1.biases

array([[-1],
       [ 1]])

In [16]:
L2.weights

array([[-0.05, -0.11]])

In [17]:
L2.biases

array([[0.]])

In [12]:
A1 = L1.forward(x1,relu)
A1

array([[1.06],
       [0.37]])

In [13]:
A2 = L2.forward(A1,sigmoid)
A2

array([[0.48]])

In [14]:
A2

array([[0.48]])